package com.example.searchbar;

public enum Place {
	Abdul_Gaffoor_Mosque ("Abdul Gaffoor Mosque",0,0),
	Al_Abrar_Mosque ("Al-Abrar Mosque",0,0),
	ArtScience_Museum ("ArtScience Museum",0,0),
	Asian_Civilisations_Museum ("Asian Civilisations Museum",0,0),
	Bright_Hill_Temple ("Bright Hill Temple",0,0),
	Buddha_Tooth_Relic_Temple ("Buddha Tooth Relic Temple",0,0),
	Bukit_Timah_Nature_Reserve ("Bukit Timah Nature Reserve",0,0),
	Cathedral_of_the_Good_Shepherd("Cathedral of the Good Shepherd",0,0),
	Central_Catchment_Nature_Reserve("Central Catchment Nature Reserve",0,0),
	Central_Sikh_Temple("Central Sikh Temple",0,0),
	Changi_Prison_Chapel_and_Museum("Changi Prison Chapel and Museum",0,0),
	Chijmes("Chijmes",0,0),
	Chinatown_Heritage_Centre("Chinatown Heritage Centre",0,0),
	Chinese_and_Japanese_Gardens("Chinese and Japanese Gardens",0,0),
	Chinese_Methodist_Church("Chinese Methodist Church",0,0),
	Church_of_St_Gregory_the_Illuminator("Church of St Gregory the Illuminator",0,0),
	Crane_Dance("Crane Dance",0,0),
	East_Coast_Park("East Coast Park",0,0),
	Esplanade_Theatres_on_the_Bay("Esplanade - Theatres on the Bay",0,0),
	Eu_Yan_Sang_Chinese_Medical_Hall("Eu Yan Sang Chinese Medical Hall",0,0),
	Fort_Canning_Park("Fort Canning Park",0,0),
	Gardens_by_the_Bay("Gardens by the Bay",0,0),
	Geylang_Serai_Market("Geylang Serai Market",0,0),
	G_Max_Reverse_Bungy("G-Max Reverse Bungy",0,0),
	Hajjah_Fatimah_Mosque("Hajjah Fatimah Mosque",0,0),
	Haw_Par_Villa("Haw Par Villa",0,0),
	HortPark("HortPark",0,0),
	House_of_Tan_Teng_Niah("House of Tan Teng Niah",0,0),
	Images_of_Singapore("Images of Singapore",0,0),
	Istana_Jamae_Mosque("Istana Jamae Mosque",0,0),
	Joo_Chiat_Street("Joo Chiat Street",0,0),
	Jurong_Bird_Park("Jurong Bird Park",0,0),
	Katong("Katong",0,0),
	Kranji_War_Memorial("Kranji War Memorial",0,0),
	Kusu_Island("Kusu Island",0,0),
	Kwan_Im_Thong_Hood_Cho_Temple("Kwan Im Thong Hood Cho Temple",0,0),
	Lau_Pa_Sat("Lau Pa Sat",0,0),
	Leong_San_See_Temple("Leong San See Temple",0,0),
	Maghain_Aboth_Synagogue("Maghain Aboth Synagogue",0,0),
	Malay_Heritage_Centre("Malay Heritage Centre",0,0),
	Malay_Village("Malay Village",0,0),
	Mandai_Orchid_Gardens("Mandai Orchid Gardens",0,0),
	Marina_Barrage("Marina Barrage",0,0),
	Marina_Bay_Sands_Casino("Marina Bay Sands Casino",0,0),
	Marina_Bay_Sands_SkyPark("Marina Bay Sands SkyPark",0,0),
	Maxwell_Road_Hawker_Centre("Maxwell Road Hawker Centre",0,0),
	Merlion_Park("Merlion Park",0,0),
	Mount_Faber_Park("Mount Faber Park",0,0),
	Nagore_Durgha_Shrine("Nagore Durgha Shrine",0,0),
	National_Museum_of_Singapore("National Museum of Singapore",0,0),
	National_Orchid_Garden("National Orchid Garden",0,0),
	NEWater_Visitor_Centre("NEWater Visitor Centre",0,0),
	Old_Parliament_House("Old Parliament House",0,0),
	Peranakan_Museum("Peranakan Museum",0,0),
	Pulau_Ubin("Palau Ubin",0,0),
	Raffles_Hotel("Raffles Hotel",0,0),
	Raffles_Place("Raffles Place",0,0),
	Red_Dot_Design_Museum("Red Dot Museum",0,0),
	Resort_World_Sentosa_Casino("Resort World Sentosa Casino",0,0),
	Sentosa_Skyline_Luge_and_Skyride("Sentosa Skyline Luge and Skyride",0,0),
	Singapore_Art_Museum("Singapore Art Museum",0,0),
	Singapore_Bazaar_and_Flea_Market("Singapore Bazaar and Flea Market",0,0),
	Singapore_Botanic_Gardens("Singapore Botanic Gardens",0,0),
	Singapore_Butterfly_and_Insect_Kingdom("Singapore Butterfly and Insect Kingdom",0,0),
	Singapore_Discovery_Centre("Singapore Discovery Centre",0,0),
	Singapore_F1_Grand_Prix("Singapore F1 Grand Prix",0,0),
	Singapore_Flyer("Singapore Flyer",0,0),
	Singapore_Mint_Coin_Gallery("Singapore Mint Coin Gallery",0,0),
	Singapore_Navy_Museum("Singapore Navy Museum",0,0),
	Singapore_Night_Safari("Singapore Night Safari",0,0),
	Singapore_Philatelic_Museum("Singapore Philatelic Museum",0,0),
	Singapore_River("Singapore River",0,0),
	Science_Centre_Singapore("Science Centre Singapore",0,0),
	Singapore_Zoo("Singapore Zoo",0,0),
	Siong_Lim_Temple("Siong Lim Temple",0,0),
	Sisters_Islands("Sisters' Islands",0,0),
	Songs_of_the_Sea("Songs of the Sea",0,0),
	Sri_Krishnan_Temple("Sri Krishnan Temple",0,0),
	Sri_Mariamman_Temple("Sri Mariamman Temple",0,0),
	Sri_Srinivasa_Perumal_Temple("Sri Srinivasa Perumal Temple",0,0),
	Sri_Thandayuthapani_Temple("Sri Thanadayuthapani Temple",0,0),
	Sri_Veeramakaliamman_Temple("Sri Veeramakaliamman Temple",0,0),
	St_Andrews_Cathedral("St Andrew's Cathedral",0,0),
	St_Johns_Island("St John's Island",0,0),
	Statues_of_Sir_Stamford_Raffles("Statue of Sir Stamford Raffles",0,0),
	Sultan_Mosque("Sultan Mosque",0,0),
	Sungei_Buloh_Nature_Park("Sungei Buloh Nature Park",0,0),
	Supreme_Court("Supreme Court",0,0),
	City_Hall("City Hall",0,0),
	Temple_of_1000_Lights("Temple of 1000 Lights",0,0),
	The_Padang("The Padang",0,0),
	The_Southern_Ridges("The Southern Ridges",0,0),
	Thian_Hock_Keng_Temple("Thian Hock Keng Temple",0,0),
	Treetop_Walk_at_MacRitchie_Reservoir("Treetop Walk at MacRitchie Reservoir",0,0),
	Underwater_World("Underwater World",0,0),
	Universal_Studios_Singapore("Universal Studios Singapore",0,0),
	Wonder_Full_at_Marina_Bay_Sands("Wonder Full at Marina Bay Sands",0,0);

	public final String name;
	public final double lng;
	public final double lat;
	
	Place(String n, double la, double ln) {
		this.name = n;
		this.lng = ln;
		this.lat = la;
	}
	

}
